### ISSUE TITLE
Move outside of Droppable area

### ISSUE THREAD

**Issue by Dalez** [colinrobertbrooks/react-beautiful-dnd-test-utils#17]
Hey, thanks for the handy package!

I was wondering if there was a way to request that an item be dropped outside of a destination, so that we can cover this bit of code:

```
    if (!result.destination) {
      return;
    }
```

Currently I'm having to ignore this bit of code in our coverage, as I can't see a way to move an item outside of the droppable area, like you can with a mouse. Maybe something like this:

```
    await makeDnd({
      getDragElement: (): Element => screen.getByText("item").closest(DND_DRAGGABLE_DATA_ATTR),
      direction: DND_OUTSIDE_DROP_AREA,
      positions: 0
    });
```

Thanks! :)

**Comment by colinrobertbrooks** [comment]
Underneath the hood this package use's `react-beautiful-dnd`'s [keyboard dragging](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/keyboard.md), and its `direction`s corresponds to [special characters](https://testing-library.com/docs/ecosystem-user-event/#special-characters) from `user-event`. With these APIs there's not a  way to drop outside of a destination.
